# Generated by Django 5.1.2 on 2024-10-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='dates',
            new_name='date',
        ),
    ]
