# Generated by Django 5.1.2 on 2024-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_rename_dates_package_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='description',
            new_name='brief_description',
        ),
        migrations.AddField(
            model_name='package',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
    ]
