# Generated by Django 5.1.2 on 2024-10-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brief_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holiday_duration', models.PositiveIntegerField()),
                ('destination', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
