# Generated by Django 5.1.2 on 2024-11-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_package_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
    ]
