# Generated by Django 5.1.2 on 2024-11-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_package_created_at_remove_package_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='holiday_type',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Relaxation', 'Relaxation'), ('Educational', 'Educational'), ('Adventurous', 'Adventurous')], default='Entertainment', max_length=25),
        ),
    ]
