# Generated by Django 5.1.2 on 2024-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_package_holiday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='holiday_type',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Relaxation', 'Relaxation'), ('Education', 'Education'), ('Adventure', 'Adventure')], default='Entertainment', max_length=25),
        ),
    ]
