# Generated by Django 5.1.2 on 2024-11-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_package_holiday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='females_only',
            field=models.BooleanField(default=False),
        ),
    ]
