# Generated by Django 5.1.2 on 2025-01-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_packageimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageImage',
            new_name='PackageImages',
        ),
    ]
