# Generated by Django 5.1.2 on 2025-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_packageimage_packageimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='detailed_description',
            new_name='getaway_highlights',
        ),
        migrations.AddField(
            model_name='package',
            name='included',
            field=models.TextField(blank=True),
        ),
    ]
