# Generated by Django 5.1.2 on 2025-01-26 15:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_package_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='getaway_highlights',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='included',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
