# Generated by Django 5.1.2 on 2025-02-01 12:43

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_package_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='detailed_description',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='getaway_highlights',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='included',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
