# Generated by Django 5.1.2 on 2025-01-31 15:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_package_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='detailed_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='getaway_highlights',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='included',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
