# Generated by Django 4.2.18 on 2025-02-02 21:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_package_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='detailed_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='getaway_highlights',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='included',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
