# Generated by Django 4.2.18 on 2025-03-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_package_created_at_package_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='holiday_type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Cultural', 'Cultural'), ('Wildlife', 'Wildlife'), ('Romantic', 'Romantic'), ('Family', 'Family'), ('Other', 'Other')], default='Adventure', max_length=25),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
