# Generated by Django 5.1.2 on 2024-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say'), ('Other', 'Other')], default='Prefer not to Say', max_length=25),
        ),
    ]
